import type { Metadata } from "next";
import { ChildrenProp } from "../type/ChildrenProp";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProp) {
    return (
        <html lang="ja">
            <body className="bg-base03 text-base0 min-h-dvh w-dvw text-base font-medium">
                {children}
            </body>
        </html>
    );
}
