import type { Metadata } from "next";
import { ChildrenProp } from "../type/ChildrenProp";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: ChildrenProp) {
    return (
        <html lang="ja">
            <body className="bg-background-body text-text-body min-h-dvh w-full text-base font-normal">
                {children}
            </body>
        </html>
    );
}
