import type { Metadata } from "next";
import { ChildrenProp } from "../type/ChildrenProp";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProp) {
    return (
        <html lang="ja">
            <body>{children}</body>
        </html>
    );
}
