services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/:cached
      - app_node_modules:/workspaces/node_modules
      - ../.docker/commandhistory:/commandhistory
    tty: true
    command: sleep infinity
    ports:
      - "18290:8080"
  database:
    image: postgres:17
    restart: always
    ports:
      - "29843:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../.docker/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=postgres --username=postgres"]
      interval: 1s
      retries: 30
      timeout: 30s
volumes:
  app_node_modules:
